export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_TO_CART = "REMOVE_TO_CART"
export const EMPTY_CART = "EMPTY_CART"
export const PRODUCT_LIST = "PRODUCT_LIST"
export const PRODUCT_SET = "PRODUCT_SET"


export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const REMOVE_TO_WISHLIST = "REMOVE_TO_WISHLIST"
export const EMPTY_WISHLIST = "EMPTY_WISHLIST"


export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"